---
version: '3.8'
volumes:
  jenkins:
    driver: local
  registry:
    driver: local
  scm:
    driver: local
services:
  jenkins:
    image: docker.io/jenkins/jenkins:2.361.2-lts
    user: root
    privileged: true
    ports:
      - 8080:8080
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - /usr/bin/docker:/usr/bin/docker:Z
  scm:
    image: docker.io/scmmanager/scm-manager:2.39.1
    container_name: scm
    ports:
      - 8081:8080
    volumes:
      - scm:/var/lib/scm:Z
  registry:
    image: docker.io/registry:2.8.1
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry:Z
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
  ui:
    image: docker.io/joxit/docker-registry-ui:2.2.0
    container_name: ui
    ports:
      - 8082:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Registre DOCKER
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - DELETE_IMAGES=true
    depends_on:
      - registry